import type {
  Document,
  DocumentAnalysis,
  ChatMessage,
  ReconciliationItem,
  Folder,
} from './types/document';

// ─── System Folders ───────────────────────────────────────────────────────────
export const mockFolders: Folder[] = [
  {
    id: 'folder-vendas',
    name: 'Vendas',
    color: '#107c10',
    icon: 'TrendingUp',
    isSystem: true,
    description: 'Faturas de clientes, notas de crédito e pro-formas',
    createdAt: '2024-01-01T00:00:00',
  },
  {
    id: 'folder-compras',
    name: 'Compras',
    color: '#0078d4',
    icon: 'ShoppingCart',
    isSystem: true,
    description: 'Faturas de fornecedores, recibos e notas de débito',
    createdAt: '2024-01-01T00:00:00',
  },
  {
    id: 'folder-tesouraria',
    name: 'Tesouraria',
    color: '#8764b8',
    icon: 'Landmark',
    isSystem: true,
    description: 'Extractos bancários, ordens de pagamento e reconciliações',
    createdAt: '2024-01-01T00:00:00',
  },
  {
    id: 'folder-rh',
    name: 'Recursos Humanos',
    color: '#d13438',
    icon: 'Users',
    isSystem: true,
    description: 'Contratos, recibos de salário e documentação de pessoal',
    createdAt: '2024-01-01T00:00:00',
  },
];



export const mockDocuments: Document[] = [
  {
    id: 'doc-001',
    name: 'Fatura_Sonangol_2024_001.pdf',
    type: 'fatura',
    status: 'analisado',
    uploadedAt: '2024-01-25T10:30:00',
    uploadedBy: 'Ana Luísa Santos',
    fileSize: 245678,
    pageCount: 3,
    amount: 5750000,
    currency: 'AOA',
    analysisId: 'ana-001',
    folderId: 'folder-compras',
    sapCategory: 'FI_SUPPLIER_INVOICE',
    sapDocNumber: '4900012301',
    accountClass: '6_custos_perdas',
    costCenter: 'CC-1001',
    nif: '5000123456',
    dueDate: '2024-02-25',
    reconciliation: { status: 'conciliado', reconciledAt: '2024-01-30T09:00:00', variance: 0 },
    tags: ['sonangol', 'combustivel', 'janeiro'],
    m365: { oneDriveUrl: 'https://onedrive.com/mock/doc001' },
  },
  {
    id: 'doc-002',
    name: 'Extrato_BFA_Janeiro_2024.pdf',
    type: 'extrato_bancario',
    status: 'analisado',
    uploadedAt: '2024-01-28T14:15:00',
    uploadedBy: 'Carlos Mendes',
    fileSize: 512340,
    pageCount: 8,
    amount: 12340000,
    currency: 'AOA',
    analysisId: 'ana-002',
    folderId: 'folder-tesouraria',
    sapCategory: 'FI_BANK_STATEMENT',
    accountClass: '4_terceiros_financeiros',
    sapDocNumber: 'EXT-BFA-2401',
    reconciliation: { status: 'conciliado', reconciledAt: '2024-02-02T10:00:00', variance: 0 },
    tags: ['bfa', 'extrato', 'janeiro'],
    m365: { oneDriveUrl: 'https://onedrive.com/mock/doc002', outlookMessageId: 'email-0023' },
  },
  {
    id: 'doc-003',
    name: 'Recibo_Pagamento_Fornecedor_003.pdf',
    type: 'recibo',
    status: 'pendente',
    uploadedAt: '2024-02-01T09:00:00',
    uploadedBy: 'Ana Luísa Santos',
    fileSize: 128900,
    pageCount: 2,
    amount: 850000,
    currency: 'AOA',
    folderId: 'folder-compras',
    sapCategory: 'FI_PAYMENT_ORDER',
    accountClass: '3_terceiros',
    reconciliation: { status: 'pendente' },
    tags: ['fornecedor', 'recibo'],
  },
  {
    id: 'doc-004',
    name: 'Contrato_Servicos_TI_2024.pdf',
    type: 'contrato',
    status: 'processando',
    uploadedAt: '2024-02-03T11:20:00',
    uploadedBy: 'João Pedro Fernandes',
    fileSize: 890123,
    pageCount: 15,
    amount: 2400000,
    currency: 'AOA',
    folderId: 'folder-rh',
    sapCategory: 'OTHER',
    accountClass: '6_custos_perdas',
    costCenter: 'CC-2002',
    tags: ['contrato', 'ti', 'servicos'],
  },
  {
    id: 'doc-005',
    name: 'Relatorio_Financeiro_Q4_2023.pdf',
    type: 'relatorio',
    status: 'analisado',
    uploadedAt: '2024-02-05T16:45:00',
    uploadedBy: 'Carlos Mendes',
    fileSize: 1240000,
    pageCount: 24,
    analysisId: 'ana-003',
    folderId: 'folder-tesouraria',
    sapCategory: 'OTHER',
    accountClass: '7_proveitos_ganhos',
    tags: ['relatorio', 'q4', '2023', 'restrito'],
  },
  {
    id: 'doc-006',
    name: 'Fatura_Unitel_Fevereiro_2024.pdf',
    type: 'fatura',
    status: 'analisado',
    uploadedAt: '2024-02-08T08:30:00',
    uploadedBy: 'Maria Conceição',
    fileSize: 98765,
    pageCount: 2,
    amount: 125000,
    currency: 'AOA',
    analysisId: 'ana-004',
    folderId: 'folder-compras',
    sapCategory: 'FI_SUPPLIER_INVOICE',
    accountClass: '6_custos_perdas',
    sapDocNumber: '4900012345',
    nif: '5000654321',
    dueDate: '2024-03-08',
    reconciliation: { status: 'conciliado', variance: 0 },
    tags: ['unitel', 'telecomunicacoes'],
    m365: { outlookMessageId: 'email-0045' },
  },
  {
    id: 'doc-007',
    name: 'Extrato_BIC_Fevereiro_2024.pdf',
    type: 'extrato_bancario',
    status: 'pendente',
    uploadedAt: '2024-02-10T10:00:00',
    uploadedBy: 'João Pedro Fernandes',
    fileSize: 456789,
    pageCount: 6,
    amount: 8900000,
    currency: 'AOA',
    folderId: 'folder-tesouraria',
    sapCategory: 'FI_BANK_STATEMENT',
    accountClass: '4_terceiros_financeiros',
    reconciliation: { status: 'divergencia', variance: 45000 },
    tags: ['bic', 'extrato'],
  },
  {
    id: 'doc-008',
    name: 'Fatura_Compra_Equipamento_IT.pdf',
    type: 'fatura',
    status: 'erro',
    uploadedAt: '2024-02-12T14:00:00',
    uploadedBy: 'Ana Luísa Santos',
    fileSize: 320000,
    pageCount: 4,
    amount: 3200000,
    currency: 'AOA',
    folderId: 'folder-compras',
    sapCategory: 'FI_SUPPLIER_INVOICE',
    accountClass: '1_activo_imobilizado',
    reconciliation: { status: 'pendente' },
    tags: ['equipamento', 'ti'],
  },
  {
    id: 'doc-009',
    name: 'Recibo_Aluguel_Escritorio_Fev.pdf',
    type: 'recibo',
    status: 'analisado',
    uploadedAt: '2024-02-15T09:15:00',
    uploadedBy: 'Maria Conceição',
    fileSize: 78900,
    pageCount: 1,
    amount: 450000,
    currency: 'AOA',
    analysisId: 'ana-005',
    folderId: 'folder-compras',
    sapCategory: 'FI_PAYMENT_ORDER',
    accountClass: '6_custos_perdas',
    reconciliation: { status: 'conciliado', variance: 0 },
    tags: ['aluguer', 'escritorio'],
  },
  {
    id: 'doc-010',
    name: 'Contrato_Fornecimento_Gas_2024.pdf',
    type: 'contrato',
    status: 'pendente',
    uploadedAt: '2024-02-18T15:30:00',
    uploadedBy: 'Carlos Mendes',
    fileSize: 560000,
    pageCount: 10,
    amount: 1800000,
    currency: 'AOA',
    folderId: 'folder-rh',
    sapCategory: 'OTHER',
    accountClass: '6_custos_perdas',
    reconciliation: { status: 'pendente' },
    tags: ['gas', 'contrato', 'fornecimento'],
  },
  {
    id: 'doc-011',
    name: 'Fatura_Angola_Cables_Marco.pdf',
    type: 'fatura',
    status: 'processando',
    uploadedAt: '2024-03-02T11:00:00',
    uploadedBy: 'Ana Luísa Santos',
    fileSize: 145000,
    pageCount: 2,
    amount: 680000,
    currency: 'AOA',
    folderId: 'folder-compras',
    sapCategory: 'FI_SUPPLIER_INVOICE',
    accountClass: '6_custos_perdas',
    sapDocNumber: '4900012401',
    tags: ['angola-cables', 'internet'],
  },
  {
    id: 'doc-012',
    name: 'Relatorio_Balanco_Fevereiro_2024.pdf',
    type: 'balanco',
    status: 'analisado',
    uploadedAt: '2024-03-05T16:00:00',
    uploadedBy: 'Carlos Mendes',
    fileSize: 890000,
    pageCount: 18,
    folderId: 'folder-tesouraria',
    sapCategory: 'OTHER',
    accountClass: '8_resultados',
    tags: ['balanco', 'fevereiro'],
  },
  {
    id: 'doc-013',
    name: 'Extrato_BNA_Marco_2024.pdf',
    type: 'extrato_bancario',
    status: 'analisado',
    uploadedAt: '2024-03-10T09:30:00',
    uploadedBy: 'João Pedro Fernandes',
    fileSize: 234000,
    pageCount: 4,
    amount: 22000000,
    currency: 'AOA',
    folderId: 'folder-tesouraria',
    sapCategory: 'FI_BANK_STATEMENT',
    accountClass: '4_terceiros_financeiros',
    reconciliation: { status: 'conciliado', variance: 0 },
    tags: ['bna', 'extrato', 'marco'],
  },
  {
    id: 'doc-014',
    name: 'Fatura_Omatapalo_Construcao.pdf',
    type: 'fatura',
    status: 'analisado',
    uploadedAt: '2024-03-12T13:00:00',
    uploadedBy: 'Maria Conceição',
    fileSize: 189000,
    pageCount: 3,
    amount: 9500000,
    currency: 'AOA',
    folderId: 'folder-compras',
    sapCategory: 'FI_SUPPLIER_INVOICE',
    accountClass: '1_activo_imobilizado',
    sapDocNumber: '4900012501',
    nif: '5001234567',
    reconciliation: { status: 'divergencia', variance: 120000 },
    tags: ['omatapalo', 'construcao', 'activo'],
  },
  {
    id: 'doc-015',
    name: 'Recibo_Seguro_Frota_2024.pdf',
    type: 'recibo',
    status: 'pendente',
    uploadedAt: '2024-03-15T10:45:00',
    uploadedBy: 'Ana Luísa Santos',
    fileSize: 112000,
    pageCount: 2,
    amount: 1200000,
    currency: 'AOA',
    folderId: 'folder-rh',
    sapCategory: 'FI_PAYMENT_ORDER',
    accountClass: '6_custos_perdas',
    reconciliation: { status: 'pendente' },
    tags: ['seguro', 'frota'],
  },
  {
    id: 'doc-016',
    name: 'Nota_Debito_BPC_Marco_2024.pdf',
    type: 'nota_debito',
    status: 'analisado',
    uploadedAt: '2024-03-18T08:00:00',
    uploadedBy: 'Carlos Mendes',
    fileSize: 89000,
    pageCount: 1,
    amount: 320000,
    currency: 'AOA',
    folderId: 'folder-tesouraria',
    sapCategory: 'FI_DEBIT_MEMO',
    accountClass: '4_terceiros_financeiros',
    sapDocNumber: 'ND-2024-032',
    reconciliation: { status: 'conciliado', variance: 0 },
    tags: ['bpc', 'nota-debito'],
  },
];

export const mockAnalyses: DocumentAnalysis[] = [
  {
    id: 'ana-001',
    documentId: 'doc-001',
    summary:
      'Fatura emitida pela Sonangol E.P. referente ao fornecimento de combustível para a frota empresarial durante o mês de janeiro de 2024. O documento inclui detalhamento de quantidades, preços unitários e totais por tipo de combustível (gasolina e gasóleo). O pagamento deverá ser efectuado em 30 dias.',
    keywords: ['combustível', 'Sonangol', 'gasolina', 'gasóleo', 'frota', 'faturação', 'janeiro'],
    tone: 'Formal / Comercial',
    signatory: 'Eng. António Silva — Director Comercial, Sonangol E.P.',
    subject: 'Fornecimento de Combustível — Janeiro 2024',
    confidentiality: 'interno',
    language: 'Português (Angola)',
    analyzedAt: '2024-01-25T11:00:00',
    extractedAmounts: { gross: 5750000, net: 5000000, tax: 750000, currency: 'AOA' },
    suggestedAccount: '62.3 — Combustíveis e Lubrificantes',
    classificationConfidence: 0.97,
  },
  {
    id: 'ana-002',
    documentId: 'doc-002',
    summary:
      'Extrato bancário do Banco de Fomento Angola (BFA) relativo ao mês de janeiro de 2024. Inclui movimentos de crédito e débito, saldo inicial e final, e referências de transferências nacionais e internacionais. Saldo final: AOA 12.340.000.',
    keywords: ['BFA', 'extrato', 'movimentos', 'transferências', 'saldo', 'janeiro', 'conta corrente'],
    tone: 'Técnico / Financeiro',
    signatory: 'BFA — Banco de Fomento Angola',
    subject: 'Extrato de Conta Corrente — Janeiro 2024',
    confidentiality: 'confidencial',
    language: 'Português (Angola)',
    analyzedAt: '2024-01-28T15:00:00',
    extractedAmounts: { gross: 12340000, currency: 'AOA' },
    suggestedAccount: '43.1 — Depósitos à Ordem',
    classificationConfidence: 0.99,
  },
  {
    id: 'ana-003',
    documentId: 'doc-005',
    summary:
      'Relatório financeiro consolidado do 4.º trimestre de 2023. Apresenta resultados operacionais, balanço patrimonial, demonstração de resultados e indicadores de desempenho financeiro. Identifica crescimento de 12% face ao período homólogo anterior.',
    keywords: ['relatório', 'trimestral', 'Q4', 'resultados', 'balanço', 'EBITDA', 'crescimento', 'DRE'],
    tone: 'Formal / Analítico',
    signatory: 'Dr. Carlos Mendes — Director Financeiro',
    subject: 'Relatório Financeiro Q4 2023',
    confidentiality: 'restrito',
    language: 'Português (Angola)',
    analyzedAt: '2024-02-05T17:30:00',
    classificationConfidence: 0.91,
  },
  {
    id: 'ana-004',
    documentId: 'doc-006',
    summary:
      'Fatura de serviços de telecomunicações da Unitel para fevereiro de 2024. Inclui serviços de voz, dados móveis e linha corporativa. O valor está dentro dos limites do contrato de empresa vigente. Sem irregularidades detectadas.',
    keywords: ['Unitel', 'telecomunicações', 'voz', 'dados', 'fevereiro', 'corporativo', 'mobile'],
    tone: 'Comercial',
    signatory: 'Unitel — Departamento de Faturação',
    subject: 'Serviços de Telecomunicações — Fevereiro 2024',
    confidentiality: 'interno',
    language: 'Português (Angola)',
    analyzedAt: '2024-02-08T09:15:00',
    extractedAmounts: { gross: 125000, net: 108696, tax: 16304, currency: 'AOA' },
    suggestedAccount: '62.2 — Telecomunicações',
    classificationConfidence: 0.95,
  },
  {
    id: 'ana-005',
    documentId: 'doc-009',
    summary:
      'Recibo de pagamento de aluguer de escritório na Rua Rainha Ginga, Luanda. Referente ao mês de fevereiro de 2024. O recibo confirma o pagamento integral do valor acordado no contrato de arrendamento.',
    keywords: ['aluguer', 'escritório', 'arrendamento', 'Luanda', 'Rua Rainha Ginga', 'imobiliário'],
    tone: 'Formal',
    signatory: 'Imobiliária Luanda Premium, Lda.',
    subject: 'Recibo de Aluguer — Fevereiro 2024',
    confidentiality: 'interno',
    language: 'Português (Angola)',
    analyzedAt: '2024-02-15T10:00:00',
    extractedAmounts: { gross: 450000, currency: 'AOA' },
    suggestedAccount: '62.1 — Rendas e Alugueres',
    classificationConfidence: 0.98,
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: 'msg-001',
    role: 'user',
    content: 'Qual é o total de faturas recebidas em janeiro de 2024?',
    sources: [],
    createdAt: '2024-02-20T14:00:00',
  },
  {
    id: 'msg-002',
    role: 'assistant',
    content:
      'Com base nos documentos analisados, em janeiro de 2024 foram registadas **2 faturas** com um total de **AOA 5.875.000**:\n\n• Fatura Sonangol E.P. — AOA 5.750.000 (Conta 62.3 — Combustíveis)\n• Fatura Unitel (referente a janeiro) — AOA 125.000 (Conta 62.2 — Telecomunicações)\n\nAmbas estão classificadas como **FI_SUPPLIER_INVOICE** no SAP/FI e devidamente conciliadas com o extrato bancário BFA de janeiro.',
    sources: [
      {
        documentId: 'doc-001',
        documentName: 'Fatura_Sonangol_2024_001.pdf',
        excerpt: '...total a pagar: 5.750.000 AOA, referente ao período de 01/01/2024 a 31/01/2024...',
        relevanceScore: 0.97,
        page: 1,
      },
      {
        documentId: 'doc-006',
        documentName: 'Fatura_Unitel_Fevereiro_2024.pdf',
        excerpt: '...serviços prestados em janeiro de 2024, total: 125.000 AOA...',
        relevanceScore: 0.84,
      },
    ],
    createdAt: '2024-02-20T14:00:05',
  },
  {
    id: 'msg-003',
    role: 'user',
    content: 'Existe algum documento com classificação restrita?',
    sources: [],
    createdAt: '2024-02-20T14:05:00',
  },
  {
    id: 'msg-004',
    role: 'assistant',
    content:
      'Sim, identifiquei **1 documento** com nível de confidencialidade **Restrito**:\n\n• **Relatório Financeiro Q4 2023** — Relatório consolidado com dados sensíveis de desempenho financeiro, assinado pelo Director Financeiro Dr. Carlos Mendes.\n\nRecomendo verificar as permissões de acesso antes de partilhar este documento. Em conformidade com os princípios do PGC-A, documentos com classificação **Restrito** devem ser acedidos apenas por utilizadores com perfil **Director** ou superior.',
    sources: [
      {
        documentId: 'doc-005',
        documentName: 'Relatorio_Financeiro_Q4_2023.pdf',
        excerpt: '...classificação: RESTRITO — acesso limitado à direcção e auditores autorizados...',
        relevanceScore: 0.99,
        page: 1,
      },
    ],
    createdAt: '2024-02-20T14:05:08',
  },
];

// ─── Reconciliation mock data ─────────────────────────────────────────────────
export const mockReconciliationItems: ReconciliationItem[] = [
  {
    id: 'rec-001',
    documentId: 'doc-001',
    documentName: 'Fatura_Sonangol_2024_001.pdf',
    documentType: 'fatura',
    bookAmount: 5750000,
    bankAmount: 5750000,
    variance: 0,
    date: '2024-01-30',
    description: 'Pagamento Sonangol — Combustível Jan 2024',
    status: 'matched',
    matchedDocumentId: 'doc-002',
  },
  {
    id: 'rec-002',
    documentId: 'doc-006',
    documentName: 'Fatura_Unitel_Fevereiro_2024.pdf',
    documentType: 'fatura',
    bookAmount: 125000,
    bankAmount: 125000,
    variance: 0,
    date: '2024-02-10',
    description: 'Pagamento Unitel — Telecomunicações',
    status: 'matched',
  },
  {
    id: 'rec-003',
    documentId: 'doc-007',
    documentName: 'Extrato_BIC_Fevereiro_2024.pdf',
    documentType: 'extrato_bancario',
    bookAmount: 8900000,
    bankAmount: 8855000,
    variance: 45000,
    date: '2024-02-15',
    description: 'Extrato BIC — Divergência identificada',
    status: 'partial',
  },
  {
    id: 'rec-004',
    documentId: 'doc-009',
    documentName: 'Recibo_Aluguel_Escritorio_Fev.pdf',
    documentType: 'recibo',
    bookAmount: 450000,
    bankAmount: 450000,
    variance: 0,
    date: '2024-02-15',
    description: 'Aluguer escritório — Luanda',
    status: 'matched',
  },
  {
    id: 'rec-005',
    documentId: 'doc-014',
    documentName: 'Fatura_Omatapalo_Construcao.pdf',
    documentType: 'fatura',
    bookAmount: 9500000,
    bankAmount: 9380000,
    variance: 120000,
    date: '2024-03-15',
    description: 'Omatapalo — Divergência de 120.000 AOA',
    status: 'partial',
  },
  {
    id: 'rec-006',
    documentId: 'doc-003',
    documentName: 'Recibo_Pagamento_Fornecedor_003.pdf',
    documentType: 'recibo',
    bookAmount: 850000,
    bankAmount: 0,
    variance: 850000,
    date: '2024-02-01',
    description: 'Recibo sem correspondência bancária',
    status: 'unmatched',
  },
  {
    id: 'rec-007',
    documentId: 'doc-016',
    documentName: 'Nota_Debito_BPC_Marco_2024.pdf',
    documentType: 'nota_debito',
    bookAmount: 320000,
    bankAmount: 320000,
    variance: 0,
    date: '2024-03-18',
    description: 'Nota de Débito BPC — Ajuste de comissões',
    status: 'matched',
  },
  {
    id: 'rec-008',
    documentId: 'doc-013',
    documentName: 'Extrato_BNA_Marco_2024.pdf',
    documentType: 'extrato_bancario',
    bookAmount: 22000000,
    bankAmount: 22000000,
    variance: 0,
    date: '2024-03-10',
    description: 'Extrato BNA — Conciliado',
    status: 'matched',
  },
];

// ─── Chart data ───────────────────────────────────────────────────────────────
export const monthlyChartData = [
  { mes: 'Set', documentos: 28, analisados: 22 },
  { mes: 'Out', documentos: 35, analisados: 30 },
  { mes: 'Nov', documentos: 42, analisados: 38 },
  { mes: 'Dez', documentos: 38, analisados: 35 },
  { mes: 'Jan', documentos: 52, analisados: 47 },
  { mes: 'Fev', documentos: 47, analisados: 31 },
];

export const docTypeData = [
  { name: 'Faturas', value: 38, color: '#0078d4' },
  { name: 'Extratos', value: 22, color: '#2b88d8' },
  { name: 'Recibos', value: 18, color: '#71afe5' },
  { name: 'Contratos', value: 12, color: '#a9d3f0' },
  { name: 'Relatórios', value: 10, color: '#c7e0f4' },
];

export const reportCashFlowData = [
  { mes: 'Jul', entradas: 18500000, saidas: 12300000 },
  { mes: 'Ago', entradas: 21000000, saidas: 14200000 },
  { mes: 'Set', entradas: 19800000, saidas: 13100000 },
  { mes: 'Out', entradas: 24500000, saidas: 15800000 },
  { mes: 'Nov', entradas: 28000000, saidas: 18200000 },
  { mes: 'Dez', entradas: 32000000, saidas: 22500000 },
];

export const sapClassData = [
  { name: 'Custos (Cl.6)', value: 42, color: '#d13438' },
  { name: 'Financeiros (Cl.4)', value: 28, color: '#0078d4' },
  { name: 'Proveitos (Cl.7)', value: 15, color: '#107c10' },
  { name: 'Activo Imob. (Cl.1)', value: 9, color: '#835b00' },
  { name: 'Resultados (Cl.8)', value: 6, color: '#8764b8' },
];
